// This file will be auto-generated by Supabase CLI
// Run: npm run db:types
// For now, this is a placeholder with basic types

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      creators: {
        Row: {
          id: string
          linkedin_url: string
          full_name: string | null
          username: string | null
          follower_count: number | null
          industry: string | null
          niche_tags: string[] | null
          status: string
          avg_engagement_rate: number | null
          total_posts_scraped: number
          last_scraped_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          linkedin_url: string
          full_name?: string | null
          username?: string | null
          follower_count?: number | null
          industry?: string | null
          niche_tags?: string[] | null
          status?: string
          avg_engagement_rate?: number | null
          total_posts_scraped?: number
          last_scraped_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          linkedin_url?: string
          full_name?: string | null
          username?: string | null
          follower_count?: number | null
          industry?: string | null
          niche_tags?: string[] | null
          status?: string
          avg_engagement_rate?: number | null
          total_posts_scraped?: number
          last_scraped_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      posts: {
        Row: {
          id: string
          creator_id: string | null
          post_url: string
          post_text: string
          posted_date: string
          likes_count: number
          comments_count: number
          reshares_count: number
          content_type: string | null
          media_urls: string[] | null
          hashtags: string[] | null
          word_count: number | null
          relevance_score: number | null
          value_depth_score: number | null
          tone_suitable: boolean | null
          final_score: number | null
          topic_category: string | null
          content_pillar: string | null
          lead_magnet_opportunity: boolean
          lead_magnet_suggestion: string | null
          ai_reasoning: string | null
          ai_analysis_duration_ms: number | null
          is_analyzed: boolean
          is_selected_for_generation: boolean
          scraped_at: string
          analyzed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          // ... (similar structure)
        }
        Update: {
          // ... (similar structure)
        }
      }
      generated_posts: {
        Row: {
          id: string
          run_id: string | null
          original_post_id: string | null
          rank: number | null
          generated_text: string
          inspiration_creator: string | null
          inspiration_url: string | null
          original_relevance: number | null
          original_value_depth: number | null
          original_final_score: number | null
          topic_category: string | null
          content_pillar: string | null
          lead_magnet_suggestion: string | null
          status: string
          scheduled_for: string | null
          published_at: string | null
          published_url: string | null
          edited_text: string | null
          internal_notes: string | null
          custom_hashtags: string[] | null
          published_likes: number | null
          published_comments: number | null
          published_reshares: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          // ... (similar structure)
        }
        Update: {
          // ... (similar structure)
        }
      }
      automation_runs: {
        Row: {
          id: string
          status: string
          started_at: string
          completed_at: string | null
          duration_seconds: number | null
          creators_total: number | null
          creators_scraped: number | null
          creators_failed: number | null
          posts_scraped: number
          posts_filtered: number
          posts_analyzed: number
          posts_generated: number
          openai_calls: number
          openai_tokens_used: number
          openai_cost_usd: number
          apify_calls: number
          apify_credits_used: number
          apify_cost_usd: number
          google_sheet_url: string | null
          google_drive_pdf_url: string | null
          supabase_pdf_url: string | null
          errors: Json
          triggered_by: string
          triggered_by_user: string | null
          created_at: string
        }
        Insert: {
          // ... (similar structure)
        }
        Update: {
          // ... (similar structure)
        }
      }
      // Additional tables...
    }
    Views: {
      v_top_posts: {
        Row: {
          // View schema
        }
      }
      v_weekly_stats: {
        Row: {
          // View schema
        }
      }
      v_creator_performance: {
        Row: {
          // View schema
        }
      }
    }
    Functions: {
      aggregate_daily_analytics: {
        Args: { target_date: string }
        Returns: void
      }
    }
  }
}
